version: '3.8'

services:
  # Serviço para o banco de dados PostgreSQL
  db:
    image: postgres
    container_name: codechella
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codechella
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - codechella-network

  # Serviço para pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9000:80"
    networks:
      - codechella-network


# Definindo redes e volumes
networks:
  codechella-network:
    driver: bridge


volumes:
  postgres_data:
    driver: local